
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'WZLottie_Example' do
  pod 'WZLottie', :path => '../'
  
  target 'WZLottie_Tests' do
    inherit! :search_paths

    
  end
end
